### ISSUE TITLE
All JXL images are actually PNG

### ISSUE THREAD

**Issue by vanontom** [zamfofex/jxl-crx#16]
Issue:
JXL images "show", but are actually PNG. Can't view or download the original JXL.

Reproduce: 
Test pages (like jpegxl.info) seem to show properly, but files are not actually JXL
"Open image in new tab" on supposed JXL image results in `file.png`
"Save image as" on supposed JXL image results in `file.png`
Brain results in `confused.jxl`

Notes:
Browser: Firefox (124.0.1) (using JPEG XL Viewer addon via addons.mozilla.org)
OS: Windows 11 (23H2, build 22631)
Can't find much documentation. Do I have some Firefox setting wrong?

**Comment by zamfofex** [comment]
You cannot get JPEG XL images to display on browsers without inbuilt JPEG XL support, so this extension has to convert them to PNGs so that the browser can display them.

**Comment by vanontom** [comment]
Thanks for the clarification. So this allows viewing of JXL by converting losslessly to PNG? Sorry, I could not find mention of "png" or conversion in docs (or Issues, Firefox Add-ons reviews,) so I thought something was wrong.

**Comment by zamfofex** [comment]
Yes, that is exactly how it works! Though it might not be “lossless” for HDR images, though I feel like that is tolerable.
