### ISSUE TITLE
Blob image size doesn't scale correctly

### ISSUE THREAD

**Issue by Yay295** [zamfofex/jxl-crx#3]
I don't know if this has anything to do with this extension, but I noticed that the `blob` images in Chrome are larger than the natively-rendered images in Firefox Nightly (I don't have this extension installed in Firefox) on https://jpegxl.info/test-page/.
Firefox:
![firefox](https://user-images.githubusercontent.com/8922038/221385249-4392cc1e-e262-4f06-8432-58f5d75e6b22.png)
Chrome:
![chrome](https://user-images.githubusercontent.com/8922038/221385257-cb26d440-7220-4bc6-9d51-a4e85e2aadf4.png)

**Comment by zamfofex** [comment]
This is because that image has a `srcset` [pixel density descriptor] of `2x` which is ignored by the extension altogether.

[pixel density descriptor]: <https://html.spec.whatwg.org/multipage/images.html#pixel-density-descriptor>
